# Generated by Django 6.0.4 on 2026-04-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pressure_kpa', models.FloatField()),
                ('label', models.CharField(choices=[('leak', 'Leak'), ('no_leak', 'No Leak')], max_length=16)),
                ('confidence_score_percent', models.FloatField()),
                ('prediction_probability', models.FloatField(blank=True, null=True)),
                ('sensor_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unstable', 'Unstable')], default='online', max_length=16)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
